### ISSUE TITLE
Issue with flowtuple3 example

### ISSUE THREAD

**Issue by sastry17** [CAIDA/pyavro-stardust#2]
Hello @salcock ,

When i use the example "flowtuple-example.py" with an sample avro file, i get errors with class initialization

Traceback (most recent call last):

  File "<ipython-input-45-e720d8f8f780>", line 1, in <module>
    runfile('/home/sastry17/pyavro-stardust/flowtuple-example.py', wdir='/home/sastry17/pyavro-stardust')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/sastry17/pyavro-stardust/flowtuple-example.py", line 51, in <module>
    runner()

  File "/home/sastry17/pyavro-stardust/flowtuple-example.py", line 36, in runner
    ftreader = AvroFlowtuple3Reader(file)

  File "src/pyavro_stardust/flowtuple3.pyx", line 55, in pyavro_stardust.flowtuple3.AvroFlowtuple3Reader.__init__
    self.currentrec = AvroFlowtuple3()

  File "src/pyavro_stardust/flowtuple3.pyx", line 10, in pyavro_stardust.flowtuple3.AvroFlowtuple3.__init__
    super().__init__(ATTR_FT3_ASN + 1, ATTR_FT3_NETACQ_COUNTRY + 1)

  File "src/pyavro_stardust/baseavro.pyx", line 88, in pyavro_stardust.baseavro.AvroRecord.__init__
    def __init__(self, numeric, strings, numarrays):

TypeError: __init__() takes exactly 3 positional arguments (2 given)

**Comment by salcock** [comment]
Hi,

Sorry about that -- I made a change yesterday that I forgot to perpetuate down to the flowtuple3 class.

Should be fixed in `master` now: `git pull origin master` should drag in the fix for you.
