### ISSUE TITLE
wandio.open error on example

### ISSUE THREAD

**Issue by sastry17** [CAIDA/pyavro-stardust#3]
Hi @salcock 

On running the example, we get an error on wandio.open . The trace is below:

limbo@sastry17:~/pyavro-stardust/examples$ python flowtuple-example.py ucsd-nt.1617235200.flowtuple.avro 
Traceback (most recent call last):
  File "flowtuple-example.py", line 43, in <module>
    run()
  File "flowtuple-example.py", line 30, in run
    ftreader.start()
  File "src/pyavro_stardust/baseavro.pyx", line 331, in pyavro_stardust.baseavro.AvroReader.start
  File "src/pyavro_stardust/baseavro.pyx", line 329, in pyavro_stardust.baseavro.AvroReader.start
  File "/home/limbo/.local/lib/python3.6/site-packages/wandio/opener.py", line 111, in wandio_open
    raise ValueError("Invalid mode. Mode must be either 'r' or 'w'")
ValueError: Invalid mode. Mode must be either 'r' or 'w'

--------------------------------------------------------------------------------------------------------------------------------------

I checked the baseavro.pyx file and i see that 'rb' is passed as an argument, while wandio.open() expects a 'r' or a 'w'

**Comment by salcock** [comment]
Yes, sorry -- there's an outstanding bug in pywandio where it cannot read binary files from local disk. The fix for this is under review right now, so it should be sorted soon.

In the meantime, you can work around this by providing your flowtuple file as a swift URI, e.g. `swift://..../ucsd-nt.1617235200.flowtuple.avro`.

**Comment by sastry17** [comment]
cool thx! 
However, i see that its the same behavior even for swift URIs.  (Trace below). But replacing the 'rb' with 'r' may work as a temporary fix, but may throw an error sometimes based on the file contents. 

limbo@sastry17:~/pyavro-stardust/examples$ python flowtuple-example.py swift://telescope-ucsdnt-avro-flowtuple-2021/datasource=ucsd-nt/year=2021/month=04/day=01/hour=00/ucsd-nt.1617235260.flowtuple.avro
Traceback (most recent call last):
  File "flowtuple-example.py", line 43, in <module>
    run()
  File "flowtuple-example.py", line 30, in run
    ftreader.start()
  File "src/pyavro_stardust/baseavro.pyx", line 331, in pyavro_stardust.baseavro.AvroReader.start
  File "src/pyavro_stardust/baseavro.pyx", line 329, in pyavro_stardust.baseavro.AvroReader.start
  File "/home/limbo/.local/lib/python3.6/site-packages/wandio/opener.py", line 111, in wandio_open
    raise ValueError("Invalid mode. Mode must be either 'r' or 'w'")
ValueError: Invalid mode. Mode must be either 'r' or 'w'

**Comment by salcock** [comment]
Yeah, hacking in an 'r' instead of 'rb' might work for swift URIs at least.

Meanwhile I'll chase up the pywandio fix and try to get that moving faster.

**Comment by sastry17** [comment]
cool, thx again!

**Comment by salcock** [comment]
I believe this was resolved some time ago, but anyone should feel free to reopen if you're still having trouble.
